"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowUpRight, CarFront } from "lucide-react";
import { api, label, money } from "@/lib/api";
import type { Car } from "@/lib/types";
import { ErrorNotice, Loading } from "./ui";
type Price={recommendedPrice:number;marketDataAvailable:boolean;drivers:{name:string;multiplier:number}[]};
type Maintenance={status:string;message?:string;monthly?:number;annual?:number;category?:string;nextServiceInKm?:number;source?:string;version?:string;disclaimer?:string};
export function CarDetail({id}:{id:string}){
 const [car,setCar]=useState<Car>();const [pricing,setPricing]=useState<Price>();const [maintenance,setMaintenance]=useState<Maintenance>();const [error,setError]=useState("");const [insightError,setInsightError]=useState("");
 useEffect(()=>{const c=new AbortController();api<Car>(`cars/${id}`,{signal:c.signal}).then(r=>setCar(r.data)).catch(e=>{if(!c.signal.aborted)setError(e.message);});Promise.all([api<Price>(`cars/${id}/pricing`,{signal:c.signal}),api<Maintenance>(`cars/${id}/maintenance`,{signal:c.signal})]).then(([p,m])=>{setPricing(p.data);setMaintenance(m.data);}).catch(()=>{if(!c.signal.aborted)setInsightError("Ownership estimates are temporarily unavailable.");});return()=>c.abort();},[id]);
 return <div className="container"><div className="page-heading"><Link className="text-link" href="/buy">← Back to cars</Link></div>{error?<ErrorNotice message={error}/>:!car?<Loading/>:<><div className="detail-layout"><div><div className="detail-image">{car.images?.length?<><div className="demo-gallery">{car.images.map(image=><img key={`${image.imageType}-${image.sortOrder}`} src={image.url} alt={`${car.brand} ${car.model} ${label(image.imageType)} view`}/>)}</div>{car.images[0]?.sourceUrl&&<p className="photo-attribution">Photo: <a href={car.images[0].sourceUrl} target="_blank" rel="noreferrer">{car.images[0].attribution||"Wikimedia Commons"}</a></p>}</>:<><CarFront size={145} strokeWidth={.7}/><p>Photos have not been published for this vehicle.</p></>}</div><div className="panel"><h2>The details</h2><dl className="details-specs">{[["Registration",car.registrationYear],["Distance",`${car.kilometers.toLocaleString()} km`],["Fuel",label(car.fuelType)],["Transmission",label(car.transmission)],["Owners",car.ownershipCount],["Body style",label(car.bodyType)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>{car.description}</p></div></div><aside><div className="panel"><div className="eyebrow muted">{car.registrationYear} · {car.city}</div><h2>{car.brand} {car.model}</h2><p>{car.variant} · {label(car.transmission)}</p><div className="price-big">{money(car.price)}</div><span className="tag">{label(car.status)}</span><div className="stack" style={{marginTop:24}}>{car.status==="LISTED"?<><Link className="button" href={`/appointment?carId=${id}`}>Arrange a viewing <ArrowUpRight size={17}/></Link><Link className="button secondary" href={`/booking?carId=${id}`}>Record purchase intent</Link></>:<p className="inline-status">This vehicle is currently unavailable for a new booking.</p>}<p className="inline-status">An appointment is required before booking. No online payment is collected.</p></div></div><div className="panel"><h3>Price perspective</h3>{pricing?<><div className="price-big">{money(pricing.recommendedPrice)}</div><p className="inline-status">{pricing.marketDataAvailable?"Estimated from listing price and configured market adjustments.":"No regional market rules are available. The current listing price is shown as the baseline."}</p>{pricing.drivers.map(d=><p key={d.name} className="inline-status">{d.name}: ×{d.multiplier}</p>)}</>:<p className="inline-status">{insightError||"Loading price perspective…"}</p>}</div></aside></div><div className="panel"><h2>A little foresight for the road ahead.</h2>{maintenance?.status==="ESTIMATE"?<><p><strong>{money(maintenance.monthly!)} / month</strong> · {money(maintenance.annual!)} annually</p><p className="inline-status">{maintenance.category}. Next scheduled service may be in approximately {maintenance.nextServiceInKm?.toLocaleString()} km.</p><small>{maintenance.disclaimer}</small></>:<p>{maintenance?.message||insightError||"Loading ownership estimates…"}</p>}</div></>}</div>;
}
