"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect,useState } from "react";
import { api,ApiError,money } from "@/lib/api";
import type { Appointment,Booking,Car,Center } from "@/lib/types";
import { ErrorNotice,Loading } from "./ui";
function authRedirect(e:unknown){if(e instanceof ApiError&&e.status===401){location.href=`/login?next=${encodeURIComponent(location.pathname+location.search)}`;return true;}return false;}
export function AppointmentForm(){
 const id=useSearchParams().get("carId");const [car,setCar]=useState<Car>();const [centers,setCenters]=useState<Center[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [result,setResult]=useState<Appointment>();
 useEffect(()=>{if(!id)return;api<Car>(`cars/${id}`).then(async r=>{setCar(r.data);setCenters((await api<Center[]>(`locations/centers?cityId=${r.data.cityId}`)).data);}).catch(e=>setError(e.message));},[id]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const startsAt=new Date(String(f.get("startsAt"))).toISOString();const r=await api<Appointment>("appointments",{method:"POST",body:JSON.stringify({carId:id,serviceCenterId:f.get("center"),startsAt,appointmentType:f.get("type"),notes:f.get("notes")})});setResult(r.data);}catch(e){if(!authRedirect(e))setError(e instanceof Error?e.message:"Please retry.");}finally{setBusy(false);}}
 return <div className="container wizard"><div className="page-heading"><div className="eyebrow muted">GET A CLOSER LOOK</div><h1>Meet your next car.</h1><p>Request a 30-minute viewing. Our team will confirm your appointment.</p></div>{error&&<ErrorNotice message={error}/>} {!id?<p>Select a car from <Link href="/buy" className="text-link">the marketplace</Link> first.</p>:result?<div className="panel"><h2>Your request is in.</h2><p>{new Date(result.startsAt).toLocaleString("en-IN")} · {result.status}</p><p className="inline-status">Reference: {result.id}</p><Link className="button" href="/profile/appointments">View appointments ↗</Link></div>:!car?<Loading/>:<div className="panel"><h2>{car.brand} {car.model}</h2><p className="inline-status">{car.city} · {money(car.price)}</p>{!centers.length?<p>No service centers are available in this city yet. Please check back.</p>:<form onSubmit={submit}><label className="field">Service center<select name="center" required><option value="">Choose a center</option>{centers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.address}</option>)}</select></label><label className="field">Appointment type<select name="type"><option value="VIEWING">Viewing</option><option value="TEST_DRIVE">Test drive</option></select></label><label className="field">Preferred date and time<input type="datetime-local" name="startsAt" required step="1800"/><small>Your local time. Choose a half-hour slot, at least one hour ahead and within 60 days. The server checks conflicts when you submit.</small></label><label className="field">Notes (optional)<textarea name="notes" maxLength={1000}/></label><button className="button" disabled={busy}>{busy?"Sending…":"Request appointment ↗"}</button></form>}</div>}</div>;
}
export function BookingForm(){
 const id=useSearchParams().get("carId");const [car,setCar]=useState<Car>();const [appointments,setAppointments]=useState<Appointment[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [result,setResult]=useState<Booking>();const [key]=useState(()=>crypto.randomUUID());
 useEffect(()=>{if(!id)return;Promise.all([api<Car>(`cars/${id}`),api<Appointment[]>("appointments/me")]).then(([c,a])=>{setCar(c.data);setAppointments(a.data.filter(x=>x.carId===id&&["CONFIRMED","COMPLETED"].includes(x.status)));}).catch(e=>{if(!authRedirect(e))setError(e.message);});},[id]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{setResult((await api<Booking>("bookings",{method:"POST",headers:{"Idempotency-Key":key},body:JSON.stringify({carId:id,appointmentId:f.get("appointment")})})).data);}catch(e){if(!authRedirect(e))setError(e instanceof Error?e.message:"Please retry.");}finally{setBusy(false);}}
 return <div className="container wizard"><div className="page-heading"><div className="eyebrow muted">YOUR NEXT STEP</div><h1>Make your move.</h1><p>Record purchase intent for your chosen car.</p></div>{error&&<ErrorNotice message={error}/>} {!id?<Link className="button" href="/buy">Choose a car</Link>:result?<div className="panel"><h2>You’re on your way.</h2><p>Booking reference: <strong>{result.bookingReference}</strong></p><p className="inline-status">Your purchase intent is recorded. No payment has been taken.</p><Link href="/profile/bookings" className="button">View your booking ↗</Link></div>:!car?<Loading/>:<div className="panel"><h2>{car.brand} {car.model}</h2><div className="price-big">{money(car.price)}</div>{!appointments.length?<p>A confirmed or completed appointment is required. <Link className="text-link" href={`/appointment?carId=${id}`}>Arrange a viewing</Link></p>:<form onSubmit={submit}><label className="field">Your appointment<select name="appointment" required>{appointments.map(a=><option key={a.id} value={a.id}>{new Date(a.startsAt).toLocaleString()} — {a.status}</option>)}</select></label><div className="notice">You can cancel a pending or confirmed booking from your account. This is a purchase-intent request; it is not a completed sale or payment.</div><label style={{display:"block",margin:"20px 0",fontSize:13}}><input type="checkbox" required/> I have reviewed the vehicle and understand the booking terms.</label><button className="button" disabled={busy}>{busy?"Recording…":"Confirm purchase intent ↗"}</button></form>}</div>}</div>;
}
