import Link from "next/link";
import { ArrowUpRight, ArrowRight, Search, SlidersHorizontal, CalendarDays, KeyRound } from "lucide-react";
import { FeaturedCars } from "@/components/featured-cars";
export default function Home() {
  return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/>GOOD CARS. NEW BEGINNINGS.</div><h1>Your next chapter.<br/><em>Your next car.</em></h1><p>From the everyday commute to the long way home.<br className="desktop"/> Find a car that feels like you.</p>
    <form action="/buy" className="hero-search"><Search size={21}/><label className="sr-only" htmlFor="home-search">Search make or model</label><input id="home-search" name="q" placeholder="Try Honda City or an SUV…"/><button aria-label="Search cars"><ArrowRight size={22}/></button></form>
    <div className="popular"><span>Start with</span>{["SUV", "Hatchback", "Sedan"].map(type => <Link key={type} href={`/buy?bodyType=${type.toUpperCase()}`}>{type}<ArrowUpRight size={12}/></Link>)}</div>
  </div><div className="hero-art" aria-label="Illustrated route through the mountains"><div className="sun"/><div className="landscape-back"/><div className="landscape-front"/><div className="road"/><div className="road-line"/><div className="road-car"><span/><i/><b/></div><span className="art-label">THE OPEN ROAD IS CALLING</span><span className="art-coordinate">18.52° N &nbsp; 73.85° E</span></div></section>
  <div className="promise-strip"><span><SlidersHorizontal size={20}/>Your budget. Your preferences.</span><span><CalendarDays size={20}/>View it before you decide.</span><span><KeyRound size={20}/>Every step, in one place.</span></div>
  <section className="section"><div className="section-heading"><div><div className="eyebrow muted">FIND YOUR FIT</div><h2>A fresh start is parked here.</h2></div><Link className="text-link" href="/buy">Explore all cars <ArrowUpRight size={18}/></Link></div><FeaturedCars/></section>
  <section className="sell-banner"><div><span className="eyebrow">MAKE ROOM FOR WHAT’S NEXT</span><h2>Goodbye, old car.<br/>Hello, new possibilities.</h2><p>Share your car’s details. Arrange an inspection.<br/>Track your sale, right from your account.</p><Link className="button dark" href="/sell">Start selling <ArrowUpRight size={18}/></Link></div><div className="sell-art" aria-hidden="true"><KeyRound size={120} strokeWidth={0.8}/><span>YOUR NEXT<br/>MOVE.</span></div></section>
  <section className="section how"><div><div className="eyebrow muted">LESS GUESSWORK. MORE GOING.</div><h2>From browsing<br/>to the driver’s seat.</h2></div><ol><li><span>01</span><div><h3>Find your kind of car</h3><p>Set your city and budget, then narrow it down to what matters to you.</p></div></li><li><span>02</span><div><h3>See it for yourself</h3><p>Request a viewing and get a closer look before making a decision.</p></div></li><li><span>03</span><div><h3>Take the next step</h3><p>Record your purchase intent and follow its progress in your account.</p></div></li></ol></section>
  <section className="section faq"><div className="eyebrow muted">A FEW THINGS TO KNOW</div><h2>Before you hit the road.</h2>{[["Can I see a car before booking?", "Yes. Request an appointment from the vehicle page. A confirmed or completed appointment is required before recording purchase intent."], ["Does booking charge my card?", "No. This platform records purchase intent. A booking does not charge you or confirm a completed purchase."], ["Are pricing and maintenance estimates guarantees?", "No. They are planning estimates based on available reference data. An inspection and actual service history provide more specific information."]].map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></>;
}
